// ============================================================================
// ISML COLLEGE LMS — PERMISSION REGISTRY
// Centralized MODULE_RESOURCE_ACTION Permission Definitions
// Enhanced with Approval Workflow and Master Finance Entitlements
// ============================================================================

import { PermissionDefinition, PermissionId } from '@/types/rbac';

export const ALL_PERMISSIONS: PermissionDefinition[] = [
  // ─── DASHBOARD ───
  {
    id: 'DASHBOARD_VIEW',
    name: 'View Super Admin Dashboard',
    module: 'DASHBOARD',
    resource: 'Dashboard',
    action: 'VIEW',
    category: 'Dashboard',
    description: 'Access the operational, academic, and system metrics overview.',
  },

  // ─── CENTRALIZED APPROVAL WORKFLOW ───
  {
    id: 'REQUEST_VIEW',
    name: 'View Approval Requests',
    module: 'APPROVALS',
    resource: 'Request',
    action: 'VIEW',
    category: 'Approvals',
    description: 'Browse all operational requests submitted for Super Admin review.',
  },
  {
    id: 'REQUEST_REVIEW',
    name: 'Review Request & Inspect Diff',
    module: 'APPROVALS',
    resource: 'Request',
    action: 'REVIEW',
    category: 'Approvals',
    description: 'Inspect item changes, validation checks, and impact analysis.',
  },
  {
    id: 'REQUEST_APPROVE',
    name: 'Approve Request (Final Authorization)',
    module: 'APPROVALS',
    resource: 'Request',
    action: 'APPROVE',
    category: 'Approvals',
    description: 'Authorize and activate submitted academic or financial changes.',
  },
  {
    id: 'REQUEST_REJECT',
    name: 'Reject Request with Reason',
    module: 'APPROVALS',
    resource: 'Request',
    action: 'REJECT',
    category: 'Approvals',
    description: 'Decline submitted operational changes with mandatory justification.',
  },
  {
    id: 'REQUEST_REQUEST_CHANGES',
    name: 'Request Changes from Submitter',
    module: 'APPROVALS',
    resource: 'Request',
    action: 'REVIEW',
    category: 'Approvals',
    description: 'Send request back to manager with correction instructions.',
  },

  // ─── ADMINISTRATION - INSTITUTIONS ───
  {
    id: 'INSTITUTION_VIEW',
    name: 'View Institutions',
    module: 'ADMINISTRATION',
    resource: 'Institution',
    action: 'VIEW',
    category: 'Administration',
    description: 'View registered college and university profiles.',
  },
  {
    id: 'INSTITUTION_CREATE',
    name: 'Create Institution',
    module: 'ADMINISTRATION',
    resource: 'Institution',
    action: 'CREATE',
    category: 'Administration',
    description: 'Register and onboard a new educational institution.',
  },
  {
    id: 'INSTITUTION_UPDATE',
    name: 'Update Institution',
    module: 'ADMINISTRATION',
    resource: 'Institution',
    action: 'UPDATE',
    category: 'Administration',
    description: 'Modify institution profile, affiliation, and contact details.',
  },
  {
    id: 'INSTITUTION_DELETE',
    name: 'Deactivate / Delete Institution',
    module: 'ADMINISTRATION',
    resource: 'Institution',
    action: 'DELETE',
    category: 'Administration',
    description: 'Archive or purge an institution from the platform.',
  },

  // ─── ADMINISTRATION - USERS ───
  {
    id: 'USER_VIEW',
    name: 'View Users',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'VIEW',
    category: 'Administration',
    description: 'Browse all users including faculty, admins, and students.',
  },
  {
    id: 'USER_CREATE',
    name: 'Create User',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'CREATE',
    category: 'Administration',
    description: 'Provision new staff, faculty, or student accounts.',
  },
  {
    id: 'USER_UPDATE',
    name: 'Update User',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'UPDATE',
    category: 'Administration',
    description: 'Update user profiles, email, department, and contact info.',
  },
  {
    id: 'USER_DELETE',
    name: 'Deactivate / Delete User',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'DELETE',
    category: 'Administration',
    description: 'Suspend, deactivate, or delete user accounts.',
  },
  {
    id: 'USER_ASSIGN_ROLE',
    name: 'Assign User Roles',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'ASSIGN',
    category: 'Administration',
    description: 'Change user roles and access entitlements.',
  },
  {
    id: 'USER_STATUS_UPDATE',
    name: 'Update User Account Status',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'UPDATE',
    category: 'Administration',
    description: 'Activate, deactivate, or suspend platform user accounts.',
  },
  {
    id: 'USER_RESET_PASSWORD',
    name: 'Reset User Password',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'UPDATE',
    category: 'Administration',
    description: 'Trigger secure password reset and credential email dispatch.',
  },
  {
    id: 'USER_VIEW_ACTIVITY',
    name: 'View User Activity Logs',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'VIEW',
    category: 'Administration',
    description: 'Inspect recent user sign-ins and session audit activity.',
  },
  {
    id: 'USER_VIEW_PERMISSIONS',
    name: 'View User Effective Permissions',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'VIEW',
    category: 'Administration',
    description: 'View granular RBAC capabilities derived from assigned role.',
  },
  {
    id: 'USER_EXPORT',
    name: 'Export User Directory',
    module: 'ADMINISTRATION',
    resource: 'User',
    action: 'EXPORT',
    category: 'Administration',
    description: 'Export registered user accounts to CSV or spreadsheet format.',
  },
  {
    id: 'STUDENT_VIEW',
    name: 'View Student Directory',
    module: 'ADMINISTRATION',
    resource: 'Student',
    action: 'VIEW',
    category: 'Administration',
    description: 'Browse enrolled students filtered by college, department, and cohort.',
  },
  {
    id: 'STUDENT_CREATE',
    name: 'Enroll / Create Student',
    module: 'ADMINISTRATION',
    resource: 'Student',
    action: 'CREATE',
    category: 'Administration',
    description: 'Provision new student learner account and academic mapping.',
  },
  {
    id: 'STUDENT_UPDATE',
    name: 'Update Student Profile',
    module: 'ADMINISTRATION',
    resource: 'Student',
    action: 'UPDATE',
    category: 'Administration',
    description: 'Update student academic details, batch, and contact details.',
  },
  {
    id: 'STUDENT_STATUS_UPDATE',
    name: 'Update Student Status',
    module: 'ADMINISTRATION',
    resource: 'Student',
    action: 'UPDATE',
    category: 'Administration',
    description: 'Activate, suspend, or update student enrollment standing.',
  },
  {
    id: 'STUDENT_VIEW_ACADEMIC',
    name: 'View Student Academic Records',
    module: 'ADMINISTRATION',
    resource: 'Student',
    action: 'VIEW',
    category: 'Administration',
    description: 'View student attendance summaries, courses, and CIA marks.',
  },
  {
    id: 'STUDENT_VIEW_ACTIVITY',
    name: 'View Student Learning Activity',
    module: 'ADMINISTRATION',
    resource: 'Student',
    action: 'VIEW',
    category: 'Administration',
    description: 'View student lecture attendance, doubts, and resource usage.',
  },
  {
    id: 'STUDENT_EXPORT',
    name: 'Export Student Records',
    module: 'ADMINISTRATION',
    resource: 'Student',
    action: 'EXPORT',
    category: 'Administration',
    description: 'Export student lists with academic hierarchy and status.',
  },

  // ─── ADMINISTRATION - ROLES ───
  {
    id: 'ROLE_VIEW',
    name: 'View Roles',
    module: 'ADMINISTRATION',
    resource: 'Role',
    action: 'VIEW',
    category: 'Administration',
    description: 'Inspect roles and their associated permission matrices.',
  },
  {
    id: 'ROLE_CREATE',
    name: 'Create Custom Role',
    module: 'ADMINISTRATION',
    resource: 'Role',
    action: 'CREATE',
    category: 'Administration',
    description: 'Define custom administrative and academic roles.',
  },
  {
    id: 'ROLE_UPDATE',
    name: 'Update Role Matrix',
    module: 'ADMINISTRATION',
    resource: 'Role',
    action: 'UPDATE',
    category: 'Administration',
    description: 'Add or remove permissions from existing roles.',
  },
  {
    id: 'ROLE_DELETE',
    name: 'Delete Role',
    module: 'ADMINISTRATION',
    resource: 'Role',
    action: 'DELETE',
    category: 'Administration',
    description: 'Delete custom roles not assigned to active users.',
  },

  // ─── ADMINISTRATION - PERMISSIONS ───
  {
    id: 'PERMISSION_VIEW',
    name: 'View Permissions Registry',
    module: 'ADMINISTRATION',
    resource: 'Permission',
    action: 'VIEW',
    category: 'Administration',
    description: 'Audit the master catalog of all system permissions.',
  },
  {
    id: 'PERMISSION_MANAGE',
    name: 'Manage System Permissions',
    module: 'ADMINISTRATION',
    resource: 'Permission',
    action: 'MANAGE',
    category: 'Administration',
    description: 'Register or calibrate permission boundaries across modules.',
  },

  // ─── ACADEMIC STRUCTURE ───
  {
    id: 'ACADEMIC_VIEW',
    name: 'View Academic Hierarchy',
    module: 'ACADEMIC',
    resource: 'Structure',
    action: 'VIEW',
    category: 'Academic',
    description: 'Navigate the complete college hierarchy from Department to Topic.',
  },
  {
    id: 'DEPARTMENT_VIEW',
    name: 'View Departments',
    module: 'ACADEMIC',
    resource: 'Department',
    action: 'VIEW',
    category: 'Academic',
    description: 'View academic departments (e.g., Computer Science, Commerce).',
  },
  {
    id: 'DEPARTMENT_CREATE',
    name: 'Create Department',
    module: 'ACADEMIC',
    resource: 'Department',
    action: 'CREATE',
    category: 'Academic',
    description: 'Establish a new department and assign HOD.',
  },
  {
    id: 'DEPARTMENT_UPDATE',
    name: 'Update Department',
    module: 'ACADEMIC',
    resource: 'Department',
    action: 'UPDATE',
    category: 'Academic',
    description: 'Edit department code, name, and HOD details.',
  },
  {
    id: 'DEPARTMENT_DELETE',
    name: 'Delete Department',
    module: 'ACADEMIC',
    resource: 'Department',
    action: 'DELETE',
    category: 'Academic',
    description: 'Remove department after unlinking programs.',
  },

  {
    id: 'PROGRAM_VIEW',
    name: 'View Programs',
    module: 'ACADEMIC',
    resource: 'Program',
    action: 'VIEW',
    category: 'Academic',
    description: 'Browse academic programs (e.g., B.Sc CS, BCA, MBA).',
  },
  {
    id: 'PROGRAM_CREATE',
    name: 'Create Program',
    module: 'ACADEMIC',
    resource: 'Program',
    action: 'CREATE',
    category: 'Academic',
    description: 'Add degree programs to departments.',
  },
  {
    id: 'PROGRAM_UPDATE',
    name: 'Update Program',
    module: 'ACADEMIC',
    resource: 'Program',
    action: 'UPDATE',
    category: 'Academic',
    description: 'Modify program duration, semester count, and status.',
  },
  {
    id: 'PROGRAM_DELETE',
    name: 'Delete Program',
    module: 'ACADEMIC',
    resource: 'Program',
    action: 'DELETE',
    category: 'Academic',
    description: 'Deactivate or delete degree programs.',
  },

  {
    id: 'BATCH_VIEW',
    name: 'View Batches',
    module: 'ACADEMIC',
    resource: 'Batch',
    action: 'VIEW',
    category: 'Academic',
    description: 'View student admission batches (e.g., 2024-2027 Batch).',
  },
  {
    id: 'BATCH_CREATE',
    name: 'Create Batch',
    module: 'ACADEMIC',
    resource: 'Batch',
    action: 'CREATE',
    category: 'Academic',
    description: 'Enroll a new academic cohort for a program.',
  },
  {
    id: 'BATCH_UPDATE',
    name: 'Update Batch',
    module: 'ACADEMIC',
    resource: 'Batch',
    action: 'UPDATE',
    category: 'Academic',
    description: 'Promote batch or modify semester progress.',
  },
  {
    id: 'BATCH_DELETE',
    name: 'Delete Batch',
    module: 'ACADEMIC',
    resource: 'Batch',
    action: 'DELETE',
    category: 'Academic',
    description: 'Remove batch archive.',
  },

  {
    id: 'SEMESTER_VIEW',
    name: 'View Semesters',
    module: 'ACADEMIC',
    resource: 'Semester',
    action: 'VIEW',
    category: 'Academic',
    description: 'Inspect program semesters and calendar schedules.',
  },
  {
    id: 'SEMESTER_CREATE',
    name: 'Create Semester',
    module: 'ACADEMIC',
    resource: 'Semester',
    action: 'CREATE',
    category: 'Academic',
    description: 'Configure new semester terms with academic years.',
  },
  {
    id: 'SEMESTER_UPDATE',
    name: 'Update Semester',
    module: 'ACADEMIC',
    resource: 'Semester',
    action: 'UPDATE',
    category: 'Academic',
    description: 'Adjust semester start/end dates and status.',
  },
  {
    id: 'SEMESTER_DELETE',
    name: 'Delete Semester',
    module: 'ACADEMIC',
    resource: 'Semester',
    action: 'DELETE',
    category: 'Academic',
    description: 'Delete empty semesters.',
  },

  {
    id: 'SUBJECT_VIEW',
    name: 'View Subjects',
    module: 'ACADEMIC',
    resource: 'Subject',
    action: 'VIEW',
    category: 'Academic',
    description: 'View subjects, credits, and faculty allocations.',
  },
  {
    id: 'SUBJECT_CREATE',
    name: 'Create Subject',
    module: 'ACADEMIC',
    resource: 'Subject',
    action: 'CREATE',
    category: 'Academic',
    description: 'Add new subjects to program semesters.',
  },
  {
    id: 'SUBJECT_UPDATE',
    name: 'Update Subject',
    module: 'ACADEMIC',
    resource: 'Subject',
    action: 'UPDATE',
    category: 'Academic',
    description: 'Edit subject credits and faculty assignments.',
  },
  {
    id: 'SUBJECT_DELETE',
    name: 'Delete Subject',
    module: 'ACADEMIC',
    resource: 'Subject',
    action: 'DELETE',
    category: 'Academic',
    description: 'Remove subject from syllabus.',
  },

  {
    id: 'MODULE_VIEW',
    name: 'View Syllabus Modules',
    module: 'ACADEMIC',
    resource: 'Module',
    action: 'VIEW',
    category: 'Academic',
    description: 'Browse curriculum units under subjects.',
  },
  {
    id: 'MODULE_CREATE',
    name: 'Create Module',
    module: 'ACADEMIC',
    resource: 'Module',
    action: 'CREATE',
    category: 'Academic',
    description: 'Define syllabus modules and learning objectives.',
  },
  {
    id: 'MODULE_UPDATE',
    name: 'Update Module',
    module: 'ACADEMIC',
    resource: 'Module',
    action: 'UPDATE',
    category: 'Academic',
    description: 'Edit module description and estimated hours.',
  },
  {
    id: 'MODULE_DELETE',
    name: 'Delete Module',
    module: 'ACADEMIC',
    resource: 'Module',
    action: 'DELETE',
    category: 'Academic',
    description: 'Remove syllabus module.',
  },

  {
    id: 'TOPIC_VIEW',
    name: 'View Topics',
    module: 'ACADEMIC',
    resource: 'Topic',
    action: 'VIEW',
    category: 'Academic',
    description: 'Inspect micro-learning topics mapped to skills.',
  },
  {
    id: 'TOPIC_CREATE',
    name: 'Create Topic',
    module: 'ACADEMIC',
    resource: 'Topic',
    action: 'CREATE',
    category: 'Academic',
    description: 'Add topic items and learning objectives.',
  },
  {
    id: 'TOPIC_UPDATE',
    name: 'Update Topic',
    module: 'ACADEMIC',
    resource: 'Topic',
    action: 'UPDATE',
    category: 'Academic',
    description: 'Update topic objectives and resource links.',
  },
  {
    id: 'TOPIC_DELETE',
    name: 'Delete Topic',
    module: 'ACADEMIC',
    resource: 'Topic',
    action: 'DELETE',
    category: 'Academic',
    description: 'Remove granular topic item.',
  },

  // ─── TEACHING & LEARNING ───
  {
    id: 'COURSE_VIEW',
    name: 'View Courses',
    module: 'LEARNING',
    resource: 'Course',
    action: 'VIEW',
    category: 'Learning',
    description: 'Browse active college courses and enrollments.',
  },
  {
    id: 'COURSE_CREATE',
    name: 'Create Course',
    module: 'LEARNING',
    resource: 'Course',
    action: 'CREATE',
    category: 'Learning',
    description: 'Setup a new course delivery container.',
  },
  {
    id: 'COURSE_UPDATE',
    name: 'Update Course',
    module: 'LEARNING',
    resource: 'Course',
    action: 'UPDATE',
    category: 'Learning',
    description: 'Update course details and faculty assignments.',
  },
  {
    id: 'COURSE_SUBMIT',
    name: 'Submit Course for Review',
    module: 'LEARNING',
    resource: 'Course',
    action: 'SUBMIT',
    category: 'Learning',
    description: 'Submit course structure to Super Admin for approval.',
  },
  {
    id: 'COURSE_APPROVE',
    name: 'Approve Course Structure',
    module: 'LEARNING',
    resource: 'Course',
    action: 'APPROVE',
    category: 'Learning',
    description: 'Authorize course publication across student portals.',
  },
  {
    id: 'COURSE_REJECT',
    name: 'Reject Course Structure',
    module: 'LEARNING',
    resource: 'Course',
    action: 'REJECT',
    category: 'Learning',
    description: 'Reject course delivery setup with explanation.',
  },
  {
    id: 'COURSE_REQUEST_CHANGES',
    name: 'Request Changes on Course',
    module: 'LEARNING',
    resource: 'Course',
    action: 'REVIEW',
    category: 'Learning',
    description: 'Ask Academic Manager to revise syllabus or topics.',
  },
  {
    id: 'COURSE_DELETE',
    name: 'Delete Course',
    module: 'LEARNING',
    resource: 'Course',
    action: 'DELETE',
    category: 'Learning',
    description: 'Archive or purge a course.',
  },
  {
    id: 'COURSE_PUBLISH',
    name: 'Publish Course',
    module: 'LEARNING',
    resource: 'Course',
    action: 'PUBLISH',
    category: 'Learning',
    description: 'Make a course live and accessible to enrolled students.',
  },

  {
    id: 'RESOURCE_VIEW',
    name: 'View Academic Resources',
    module: 'LEARNING',
    resource: 'Resource',
    action: 'VIEW',
    category: 'Learning',
    description: 'Access the college digital library and handouts.',
  },
  {
    id: 'RESOURCE_CREATE',
    name: 'Upload Resource',
    module: 'LEARNING',
    resource: 'Resource',
    action: 'CREATE',
    category: 'Learning',
    description: 'Upload lecture slides, notes, and worksheets.',
  },
  {
    id: 'RESOURCE_UPDATE',
    name: 'Update Resource',
    module: 'LEARNING',
    resource: 'Resource',
    action: 'UPDATE',
    category: 'Learning',
    description: 'Edit resource metadata and replace attachments.',
  },
  {
    id: 'RESOURCE_DELETE',
    name: 'Delete Resource',
    module: 'LEARNING',
    resource: 'Resource',
    action: 'DELETE',
    category: 'Learning',
    description: 'Delete or archive inappropriate materials.',
  },
  {
    id: 'RESOURCE_APPROVE',
    name: 'Approve Resource',
    module: 'LEARNING',
    resource: 'Resource',
    action: 'APPROVE',
    category: 'Learning',
    description: 'Review and approve resources uploaded by faculty.',
  },
  {
    id: 'RESOURCE_PUBLISH',
    name: 'Publish Resource',
    module: 'LEARNING',
    resource: 'Resource',
    action: 'PUBLISH',
    category: 'Learning',
    description: 'Release approved materials to student portals.',
  },

  {
    id: 'CLASS_VIEW',
    name: 'View Class Sessions',
    module: 'LEARNING',
    resource: 'Class',
    action: 'VIEW',
    category: 'Learning',
    description: 'Monitor live, upcoming, and completed classroom sessions.',
  },
  {
    id: 'CLASS_CREATE',
    name: 'Schedule Class',
    module: 'LEARNING',
    resource: 'Class',
    action: 'CREATE',
    category: 'Learning',
    description: 'Create individual lecture sessions or live links.',
  },
  {
    id: 'CLASS_UPDATE',
    name: 'Update Class',
    module: 'LEARNING',
    resource: 'Class',
    action: 'UPDATE',
    category: 'Learning',
    description: 'Reschedule or change faculty for a class.',
  },
  {
    id: 'CLASS_CANCEL',
    name: 'Cancel Class',
    module: 'LEARNING',
    resource: 'Class',
    action: 'CANCEL',
    category: 'Learning',
    description: 'Cancel an upcoming scheduled class session.',
  },

  {
    id: 'ASSESSMENT_VIEW',
    name: 'View Assessments',
    module: 'LEARNING',
    resource: 'Assessment',
    action: 'VIEW',
    category: 'Learning',
    description: 'Browse mid-terms, semester exams, and homework assignments.',
  },
  {
    id: 'ASSESSMENT_CREATE',
    name: 'Create Assessment',
    module: 'LEARNING',
    resource: 'Assessment',
    action: 'CREATE',
    category: 'Learning',
    description: 'Publish new exams, quizzes, or assignments.',
  },
  {
    id: 'ASSESSMENT_UPDATE',
    name: 'Update Assessment',
    module: 'LEARNING',
    resource: 'Assessment',
    action: 'UPDATE',
    category: 'Learning',
    description: 'Edit due dates and grading criteria.',
  },
  {
    id: 'ASSESSMENT_DELETE',
    name: 'Delete Assessment',
    module: 'LEARNING',
    resource: 'Assessment',
    action: 'DELETE',
    category: 'Learning',
    description: 'Remove assessment items.',
  },

  // ─── SCHEDULING ───
  {
    id: 'TIMETABLE_VIEW',
    name: 'View Timetable',
    module: 'SCHEDULING',
    resource: 'Timetable',
    action: 'VIEW',
    category: 'Scheduling',
    description: 'Inspect the weekly timetable grid for departments & batches.',
  },
  {
    id: 'TIMETABLE_CREATE',
    name: 'Create Timetable Slot',
    module: 'SCHEDULING',
    resource: 'Timetable',
    action: 'CREATE',
    category: 'Scheduling',
    description: 'Allocate period, room, and faculty for batch timetable.',
  },
  {
    id: 'TIMETABLE_UPDATE',
    name: 'Update Timetable Slot',
    module: 'SCHEDULING',
    resource: 'Timetable',
    action: 'UPDATE',
    category: 'Scheduling',
    description: 'Modify room or faculty allocations on timetable grid.',
  },
  {
    id: 'TIMETABLE_DELETE',
    name: 'Delete Timetable Slot',
    module: 'SCHEDULING',
    resource: 'Timetable',
    action: 'DELETE',
    category: 'Scheduling',
    description: 'Remove slot from schedule.',
  },

  // ─── MASTER FINANCE ───
  {
    id: 'FEE_STRUCTURE_VIEW',
    name: 'View Fee Structures',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'VIEW',
    category: 'Finance',
    description: 'Browse college, program, and semester fee schedules.',
  },
  {
    id: 'FEE_STRUCTURE_CREATE',
    name: 'Create Fee Structure',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'CREATE',
    category: 'Finance',
    description: 'Build fee schedules with component line items.',
  },
  {
    id: 'FEE_STRUCTURE_UPDATE',
    name: 'Update Fee Structure',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'UPDATE',
    category: 'Finance',
    description: 'Edit draft or revise existing fee structures.',
  },
  {
    id: 'FEE_STRUCTURE_SUBMIT',
    name: 'Submit Fee Structure for Review',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'SUBMIT',
    category: 'Finance',
    description: 'Finance Manager submits fee schedules to Super Admin.',
  },
  {
    id: 'FEE_STRUCTURE_REVIEW',
    name: 'Review Fee Structure Diff',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'REVIEW',
    category: 'Finance',
    description: 'Super Admin audits fee component amounts and impact.',
  },
  {
    id: 'FEE_STRUCTURE_APPROVE',
    name: 'Approve Fee Structure',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'APPROVE',
    category: 'Finance',
    description: 'Super Admin authorizes fee schedule for billing.',
  },
  {
    id: 'FEE_STRUCTURE_REJECT',
    name: 'Reject Fee Structure',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'REJECT',
    category: 'Finance',
    description: 'Decline fee structure proposal with reason.',
  },
  {
    id: 'FEE_STRUCTURE_REQUEST_CHANGES',
    name: 'Request Changes on Fee Structure',
    module: 'FINANCE',
    resource: 'FeeStructure',
    action: 'REVIEW',
    category: 'Finance',
    description: 'Ask Finance Manager to adjust specific fee components.',
  },

  {
    id: 'FEE_COMPONENT_VIEW',
    name: 'View Fee Components',
    module: 'FINANCE',
    resource: 'FeeComponent',
    action: 'VIEW',
    category: 'Finance',
    description: 'Inspect catalog of Tuition, Lab, Exam fee components.',
  },
  {
    id: 'FEE_COMPONENT_CREATE',
    name: 'Create Fee Component',
    module: 'FINANCE',
    resource: 'FeeComponent',
    action: 'CREATE',
    category: 'Finance',
    description: 'Register new billing fee item categories.',
  },
  {
    id: 'FEE_COMPONENT_UPDATE',
    name: 'Update Fee Component',
    module: 'FINANCE',
    resource: 'FeeComponent',
    action: 'UPDATE',
    category: 'Finance',
    description: 'Modify fee component descriptions or defaults.',
  },
  {
    id: 'FEE_COMPONENT_DELETE',
    name: 'Delete Fee Component',
    module: 'FINANCE',
    resource: 'FeeComponent',
    action: 'DELETE',
    category: 'Finance',
    description: 'Deactivate unused fee component items.',
  },

  {
    id: 'DISCOUNT_VIEW',
    name: 'View Scholarships & Discounts',
    module: 'FINANCE',
    resource: 'Discount',
    action: 'VIEW',
    category: 'Finance',
    description: 'Browse merit concessions and institutional waivers.',
  },
  {
    id: 'DISCOUNT_CREATE',
    name: 'Create Scholarship / Discount',
    module: 'FINANCE',
    resource: 'Discount',
    action: 'CREATE',
    category: 'Finance',
    description: 'Define scholarship criteria and discount percentages.',
  },
  {
    id: 'DISCOUNT_UPDATE',
    name: 'Update Scholarship / Discount',
    module: 'FINANCE',
    resource: 'Discount',
    action: 'UPDATE',
    category: 'Finance',
    description: 'Modify eligibility and discount values.',
  },
  {
    id: 'DISCOUNT_APPROVE',
    name: 'Approve Discount Policy',
    module: 'FINANCE',
    resource: 'Discount',
    action: 'APPROVE',
    category: 'Finance',
    description: 'Authorize discount rule for student fee invoices.',
  },
  {
    id: 'DISCOUNT_REJECT',
    name: 'Reject Discount Policy',
    module: 'FINANCE',
    resource: 'Discount',
    action: 'REJECT',
    category: 'Finance',
    description: 'Reject proposed scholarship schemes.',
  },

  {
    id: 'PAYMENT_POLICY_VIEW',
    name: 'View Payment Policies',
    module: 'FINANCE',
    resource: 'PaymentPolicy',
    action: 'VIEW',
    category: 'Finance',
    description: 'View installments, grace periods, and late fees.',
  },
  {
    id: 'PAYMENT_POLICY_CREATE',
    name: 'Create Payment Policy',
    module: 'FINANCE',
    resource: 'PaymentPolicy',
    action: 'CREATE',
    category: 'Finance',
    description: 'Configure fee installment plans and schedules.',
  },
  {
    id: 'PAYMENT_POLICY_UPDATE',
    name: 'Update Payment Policy',
    module: 'FINANCE',
    resource: 'PaymentPolicy',
    action: 'UPDATE',
    category: 'Finance',
    description: 'Adjust due dates and penalty terms.',
  },
  {
    id: 'PAYMENT_POLICY_APPROVE',
    name: 'Approve Payment Policy',
    module: 'FINANCE',
    resource: 'PaymentPolicy',
    action: 'APPROVE',
    category: 'Finance',
    description: 'Authorize installment rules for college portal.',
  },
  {
    id: 'PAYMENT_POLICY_REJECT',
    name: 'Reject Payment Policy',
    module: 'FINANCE',
    resource: 'PaymentPolicy',
    action: 'REJECT',
    category: 'Finance',
    description: 'Decline proposed installment configurations.',
  },

  {
    id: 'REFUND_POLICY_VIEW',
    name: 'View Refund Policies',
    module: 'FINANCE',
    resource: 'RefundPolicy',
    action: 'VIEW',
    category: 'Finance',
    description: 'Inspect university and college withdrawal refund rules.',
  },
  {
    id: 'REFUND_POLICY_CREATE',
    name: 'Create Refund Policy',
    module: 'FINANCE',
    resource: 'RefundPolicy',
    action: 'CREATE',
    category: 'Finance',
    description: 'Add admission cancellation and refund schedules.',
  },
  {
    id: 'REFUND_POLICY_UPDATE',
    name: 'Update Refund Policy',
    module: 'FINANCE',
    resource: 'RefundPolicy',
    action: 'UPDATE',
    category: 'Finance',
    description: 'Modify withdrawal windows and deduction slabs.',
  },
  {
    id: 'REFUND_POLICY_APPROVE',
    name: 'Approve Refund Policy',
    module: 'FINANCE',
    resource: 'RefundPolicy',
    action: 'APPROVE',
    category: 'Finance',
    description: 'Authorize official college refund regulations.',
  },
  {
    id: 'REFUND_POLICY_REJECT',
    name: 'Reject Refund Policy',
    module: 'FINANCE',
    resource: 'RefundPolicy',
    action: 'REJECT',
    category: 'Finance',
    description: 'Decline proposed refund guidelines.',
  },

  {
    id: 'FINANCE_REPORT_VIEW',
    name: 'View Finance Reports',
    module: 'FINANCE',
    resource: 'FinanceReport',
    action: 'VIEW',
    category: 'Finance',
    description: 'Access expected vs collected college fee aggregates.',
  },
  {
    id: 'FINANCE_REPORT_EXPORT',
    name: 'Export Finance Reports',
    module: 'FINANCE',
    resource: 'FinanceReport',
    action: 'EXPORT',
    category: 'Finance',
    description: 'Download CSV and Excel fee collection audit sheets.',
  },
  {
    id: 'FINANCE_AUDIT_VIEW',
    name: 'View Finance Audit Trail',
    module: 'FINANCE',
    resource: 'FinanceAudit',
    action: 'VIEW',
    category: 'Finance',
    description: 'Inspect who proposed, submitted, and approved fee modifications.',
  },

  // ─── MONITORING ───
  {
    id: 'ATTENDANCE_VIEW',
    name: 'Monitor Attendance',
    module: 'MONITORING',
    resource: 'Attendance',
    action: 'VIEW',
    category: 'Monitoring',
    description: 'Track department-wise and batch-wise attendance rates.',
  },
  {
    id: 'RESULT_VIEW',
    name: 'Monitor Academic Results',
    module: 'MONITORING',
    resource: 'Result',
    action: 'VIEW',
    category: 'Monitoring',
    description: 'View exam scores, pass percentages, and GPA trends.',
  },
  {
    id: 'REPORT_VIEW',
    name: 'View Analytics & Reports',
    module: 'MONITORING',
    resource: 'Report',
    action: 'VIEW',
    category: 'Monitoring',
    description: 'Access institutional compliance and performance reports.',
  },
  {
    id: 'REPORT_EXPORT',
    name: 'Export Official Reports',
    module: 'MONITORING',
    resource: 'Report',
    action: 'EXPORT',
    category: 'Monitoring',
    description: 'Download CSV, Excel, or PDF audit reports.',
  },

  // ─── COMMUNICATION ───
  {
    id: 'NOTIFICATION_VIEW',
    name: 'View System Notifications',
    module: 'COMMUNICATION',
    resource: 'Notification',
    action: 'VIEW',
    category: 'Communication',
    description: 'Audit college broadcasts and alerts.',
  },
  {
    id: 'NOTIFICATION_CREATE',
    name: 'Compose Announcement',
    module: 'COMMUNICATION',
    resource: 'Notification',
    action: 'CREATE',
    category: 'Communication',
    description: 'Draft announcements for students, faculty, or staff.',
  },
  {
    id: 'NOTIFICATION_SEND',
    name: 'Broadcast Notification',
    module: 'COMMUNICATION',
    resource: 'Notification',
    action: 'SEND',
    category: 'Communication',
    description: 'Dispatch push and email alerts to target groups.',
  },

  // ─── SYSTEM ───
  {
    id: 'AUDIT_LOG_VIEW',
    name: 'View Audit Logs',
    module: 'SYSTEM',
    resource: 'AuditLog',
    action: 'VIEW',
    category: 'System',
    description: 'Track immutable administrative actions and IP footprints.',
  },
  {
    id: 'SYSTEM_MONITORING_VIEW',
    name: 'View System Telemetry',
    module: 'SYSTEM',
    resource: 'Monitoring',
    action: 'VIEW',
    category: 'System',
    description: 'Check service uptime, database health, and latency.',
  },
  {
    id: 'SYSTEM_SETTINGS_VIEW',
    name: 'View System Settings',
    module: 'SYSTEM',
    resource: 'Settings',
    action: 'VIEW',
    category: 'System',
    description: 'Inspect college branding, session timers, and configurations.',
  },
  {
    id: 'SYSTEM_SETTINGS_UPDATE',
    name: 'Update System Settings',
    module: 'SYSTEM',
    resource: 'Settings',
    action: 'UPDATE',
    category: 'System',
    description: 'Save global LMS preferences and operational parameters.',
  },
];

export const PERMISSION_MAP: Record<PermissionId, PermissionDefinition> = ALL_PERMISSIONS.reduce(
  (acc, curr) => {
    acc[curr.id] = curr;
    return acc;
  },
  {} as Record<PermissionId, PermissionDefinition>
);

export const PERMISSION_CATEGORIES = [
  'Dashboard',
  'Approvals',
  'Administration',
  'Academic',
  'Learning',
  'Scheduling',
  'Finance',
  'Monitoring',
  'Communication',
  'System',
] as const;

export const ALL_PERMISSION_IDS: PermissionId[] = ALL_PERMISSIONS.map((p) => p.id);

// ─── ROLE PERMISSION ENTITLEMENTS ───
export const SUPER_ADMIN_PERMISSIONS: PermissionId[] = [...ALL_PERMISSION_IDS];

export const ACADEMIC_COORDINATOR_PERMISSIONS: PermissionId[] = [
  'DASHBOARD_VIEW',
  'REQUEST_VIEW',
  'ACADEMIC_VIEW',
  'DEPARTMENT_VIEW',
  'DEPARTMENT_CREATE',
  'DEPARTMENT_UPDATE',
  'PROGRAM_VIEW',
  'PROGRAM_CREATE',
  'PROGRAM_UPDATE',
  'BATCH_VIEW',
  'BATCH_CREATE',
  'BATCH_UPDATE',
  'SEMESTER_VIEW',
  'SEMESTER_CREATE',
  'SEMESTER_UPDATE',
  'SUBJECT_VIEW',
  'SUBJECT_CREATE',
  'SUBJECT_UPDATE',
  'MODULE_VIEW',
  'MODULE_CREATE',
  'MODULE_UPDATE',
  'TOPIC_VIEW',
  'TOPIC_CREATE',
  'TOPIC_UPDATE',
  'COURSE_VIEW',
  'COURSE_CREATE',
  'COURSE_UPDATE',
  'COURSE_SUBMIT',
  'RESOURCE_VIEW',
  'RESOURCE_CREATE',
  'RESOURCE_UPDATE',
  'RESOURCE_APPROVE',
  'RESOURCE_PUBLISH',
  'CLASS_VIEW',
  'CLASS_CREATE',
  'CLASS_UPDATE',
  'TIMETABLE_VIEW',
  'TIMETABLE_CREATE',
  'TIMETABLE_UPDATE',
  'ATTENDANCE_VIEW',
  'RESULT_VIEW',
  'REPORT_VIEW',
  'STUDENT_VIEW',
  'STUDENT_CREATE',
  'NOTIFICATION_VIEW',
  'NOTIFICATION_CREATE',
];

export const FINANCE_MANAGER_PERMISSIONS: PermissionId[] = [
  'DASHBOARD_VIEW',
  'REQUEST_VIEW',
  'FEE_STRUCTURE_VIEW',
  'FEE_STRUCTURE_CREATE',
  'FEE_STRUCTURE_UPDATE',
  'FEE_STRUCTURE_SUBMIT',
  'FEE_COMPONENT_VIEW',
  'FEE_COMPONENT_CREATE',
  'FEE_COMPONENT_UPDATE',
  'DISCOUNT_VIEW',
  'DISCOUNT_CREATE',
  'DISCOUNT_UPDATE',
  'PAYMENT_POLICY_VIEW',
  'PAYMENT_POLICY_CREATE',
  'PAYMENT_POLICY_UPDATE',
  'REFUND_POLICY_VIEW',
  'REFUND_POLICY_CREATE',
  'REFUND_POLICY_UPDATE',
  'FINANCE_REPORT_VIEW',
  'FINANCE_REPORT_EXPORT',
  'FINANCE_AUDIT_VIEW',
  'NOTIFICATION_VIEW',
];

export const AUDITOR_VIEW_ONLY_PERMISSIONS: PermissionId[] = [
  'DASHBOARD_VIEW',
  'REQUEST_VIEW',
  'INSTITUTION_VIEW',
  'USER_VIEW',
  'STUDENT_VIEW',
  'ROLE_VIEW',
  'PERMISSION_VIEW',
  'ACADEMIC_VIEW',
  'DEPARTMENT_VIEW',
  'PROGRAM_VIEW',
  'BATCH_VIEW',
  'SEMESTER_VIEW',
  'SUBJECT_VIEW',
  'COURSE_VIEW',
  'RESOURCE_VIEW',
  'CLASS_VIEW',
  'TIMETABLE_VIEW',
  'FEE_STRUCTURE_VIEW',
  'FEE_COMPONENT_VIEW',
  'DISCOUNT_VIEW',
  'PAYMENT_POLICY_VIEW',
  'REFUND_POLICY_VIEW',
  'FINANCE_REPORT_VIEW',
  'FINANCE_AUDIT_VIEW',
  'ATTENDANCE_VIEW',
  'RESULT_VIEW',
  'REPORT_VIEW',
  'REPORT_EXPORT',
  'AUDIT_LOG_VIEW',
  'SYSTEM_MONITORING_VIEW',
  'SYSTEM_SETTINGS_VIEW',
];
